version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_bazar
    restart: always
    environment:
      POSTGRES_USER: bazaruser
      POSTGRES_PASSWORD: bazarpass
      POSTGRES_DB: bazardb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 